// Generated by jextract

package se.curl;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef int (*curl_sshkeycallback)(CURL *, const struct curl_khkey {
 *     const char *key;
 *     size_t len;
 *     enum curl_khtype keytype;
 * } *, const struct curl_khkey {
 *     const char *key;
 *     size_t len;
 *     enum curl_khtype keytype;
 * } *, enum curl_khmatch {
 *     CURLKHMATCH_OK,
 *     CURLKHMATCH_MISMATCH,
 *     CURLKHMATCH_MISSING,
 *     CURLKHMATCH_LAST
 * }, void *)
 * }
 */
public class curl_sshkeycallback {

    curl_sshkeycallback() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        int apply(MemorySegment easy, MemorySegment knownkey, MemorySegment foundkey, int _x3, MemorySegment clientp);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
        curl_h.C_INT,
        curl_h.C_POINTER,
        curl_h.C_POINTER,
        curl_h.C_POINTER,
        curl_h.C_INT,
        curl_h.C_POINTER
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = curl_h.upcallHandle(curl_sshkeycallback.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(curl_sshkeycallback.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static int invoke(MemorySegment funcPtr,MemorySegment easy, MemorySegment knownkey, MemorySegment foundkey, int _x3, MemorySegment clientp) {
        try {
            return (int) DOWN$MH.invokeExact(funcPtr, easy, knownkey, foundkey, _x3, clientp);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

